version: '3'
services:
  pricing:
    build: ./pricing
    expose:
    - '3000' 
    environment:
      COINMARKETCAP_API_TOKEN="$COINMARKETCAP_API_TOKEN"
  ranking:
    build: ./ranking
    expose:
    - '3000' 
    environment:
      CRYPTOCOMPARE_API_TOKEN="$CRYPTOCOMPARE_API_TOKEN"
  api:
    build: ./api
    ports:
    - '3000:3000' 
